### ISSUE TITLE
Hero death

### ISSUE THREAD

**Issue by kra53n** [MbIUIb/space_game#4]
@MbIUIb

The question is about processing of player death.

https://github.com/MbIUIb/space_game/blob/377a204a68b081f2672c2f7fdaab9c2551bd0d8e/game/starships.py#L86-L87

I think we could check of the player death not in a class but in main loop of the game. It will be advantage because if we will implement states for the game (e.g. menu state, play state, settings state, etc) we could easily change state to other. And also we could get rid of `hero` bool.

https://github.com/MbIUIb/space_game/blob/377a204a68b081f2672c2f7fdaab9c2551bd0d8e/game/starships.py#L79

**Comment by mbiuib** [comment]
Yes, I was thinking about it, so I left the stub for now
